job-aggregator:
  version: @project.version@

server:
  port: 8080

spring:
  datasource:
    url: test_url
    username: login
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

