job-aggregator:
  version: @project.version@

server:
  port: 8080

spring:
  datasource:
    url: localhost:1521/XEPDB1
    username: JOB_DEV
    password: JOB_DEV
    driver-class-name: oracle.jdbc.OracleDriver

# jdbc:oracle:thin:@porasbbselscan.sbb.ch:1551/zps_entw
# localhost:5500/em
