job-aggregator:
  version: 1.0-SNAPSHOT

server:
  port: 8080

spring:
  datasource:
    url: localhost:1521/XEPDB1
    username: SYSTEM
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

# jdbc:oracle:thin:@porasbbselscan.sbb.ch:1551/zps_entw
# localhost:5500/em
